name: azka_userbot_telegram
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  general_lib: ^0.0.16
  http: ^1.1.2
  path: ^1.9.0
  telegram_client: ^0.6.0
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
