name: userbot_telegram
description: GENERAL FOSS userbot telegram simple by GENERAL FOSS dev.
version: 0.0.0
repository: https://github.com/generalfoss/userbot_telegram.git
homepage: https://github.com/generalfoss/userbot_telegram.git
issue_tracker: https://github.com/generalfoss/userbot_telegram.git

environment:
  sdk: ^3.2.3

# Add regular dependencies here.
dependencies:
  general_lib: ^0.0.27
  http: ^1.1.2
  mason_logger: ^0.2.12
  packagex: ^0.0.44
  path: ^1.9.0
  telegram_client: ^0.8.0
  translate_client: ^0.0.2
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.1.0
  test: ^1.24.0
